spring.application.name=financemanager
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/financemanager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:eOM7bqyRa5k2WHiLYXAGoeb1kC/kw0XZQsx8wmsEs7bdhPYHDzULe9U4d7gOwPLut+l3qlBn5+4Rkls5XPxsbQ==}
jwt.access-token-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:900000}
jwt.refresh-token-expiration-days=${JWT_REFRESH_EXPIRATION_DAYS:30}
