spring.application.name=financemanager
spring.datasource.url=jdbc:postgresql://localhost:5432/financemanager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
jwt.secret=eOM7bqyRa5k2WHiLYXAGoeb1kC/kw0XZQsx8wmsEs7bdhPYHDzULe9U4d7gOwPLut+l3qlBn5+4Rkls5XPxsbQ==
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-days=30